spring:
  profiles:
    active: local
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
  datasource:
    url: jdbc:h2:tcp://localhost/~/guestbook
    #jdbc:mariadb://localhost:3307/db명
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: true #default : true
  thymeleaf:
    cache: false

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace
